artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/MahraibFatima/100DaysOf-Bytewise/raw/main/Projects/WineQualityPrediction/winequality-data.zip
  local_data_file: artifacts/data_ingestion/WineQualityDataset.zip
  unzip_dir: artifacts/data_ingestion
